### ISSUE TITLE
unssuficent permissions to run tests on jdk16 and up

### ISSUE THREAD

**Issue by judovana** [jnr/jnr-enxio#37]
hi!

There are rqured more  opens to run on jdk16 and up.

```
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M5</version>
        <configuration>
        <argLine>--add-opens java.base/java.io=ALL-UNNAMED</argLine>
        </configuration>
      </plugin>
```

added to pom is fixing the issue, but is beaking jdk8 compatibility.  So it most likley belongs to the java9profile, but I'm not sure how maintained that is.

**Comment by headius** [comment]
This library should be presenting at least an automatic module name, so I think we could narrow this to just the library itself... but modifying the build to do the right flags is a bit more work. Will address this after a round of releases.
