### ISSUE TITLE
Hamcrest-parent dependency not available

### ISSUE THREAD

**Issue by rektide** [jnr/jnr-enxio#5]
When trying to build, I get an error about an unavailable Hamcrest;

`[ERROR] Failed to execute goal on project jnr-enxio: Could not resolve dependencies for project com.github.jnr:jnr-enxio:jar:0.2-SNAPSHOT: Failed to collect dependencies for [junit:junit:jar:[4.5,5.0) (test), org.jruby.extras:jnr-constants:jar:[0.8,1.0) (compile), com.github.jnr:jnr-ffi:jar:[0.7.0,0.8.0) (compile)]: Failed to read artifact descriptor for org.hamcrest:hamcrest-core:jar:1.3-redhat-1: Failure to find org.hamcrest:hamcrest-parent:pom:1.3-redhat-1 in http://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository-group has elapsed or updates are forced -> [Help 1]`

I've tried building Hamcrest myself but ran into issues getting their bundle target to work. Those issues are in: hamcrest/JavaHamcrest#75 . Even after I get their bundle running, it appears I still have to manually install or publish the build artifacts that their ant tools produce. :/

**Comment by headius** [comment]
Very old and unlikely to still be a problem. Let us know if it is.
