### ISSUE TITLE
Why doesn't NativeServerSocketChannel implement ByteChannel ?

### ISSUE THREAD

**Issue by hznut** [jnr/jnr-enxio#7]
1. Why doesn't NativeServerSocketChannel implement ByteChannel unlike the NativeSocketChannel which does. It implies that one can't read/write to a server socket channel. Why is that ? From looking at an example in the unixsocket project I see that one needs to register another NativeSocketChannel with the  server channel in order to read.

2. How about unix datagram sockets ? Is there a notion of a server socket for these type of sockets ? If yes then from what I understand there's no need of an accept for a unix datagram server socket.

3. The library that you guys have written is very helpful. I'd appreciate if some documentation can be added to explain some of the concepts. Eg. a server can do bind, accept etc.

* My knowledge of unix socket concepts is very limited so please pardon any dumb questions.

**Comment by hznut** [comment]
The issue I opened is more like a comment. What is there a better place for comment/discussions around code on github ?

**Comment by headius** [comment]
Server sockets are not byte streams, are they? What does it mean to read from a server socket? You have to accept a connection to do any reading and writing, no?

**Comment by headius** [comment]
Oh, and there's also an issue jnr/jnr-unixsocket#22 for adding SOCK_DGRAM support, which may require change to enxio as well.

**Comment by headius** [comment]
1. I don't believe ByteChannel makes sense for a server socket, since as far as I know all server sockets can do is accept connections. If I'm wrong, open a new issue just for that feature.

2. SOCK_DGRAM is filed as jnr/jnr-unixsocket#22.

3. I will open a separate issue for missing documentation.
