### ISSUE TITLE
request for license clarification for channels/PollSelectionKey.java

### ISSUE THREAD

**Issue by tmancill** [jnr/jnr-enxio#8]
Hi,

We're in the midst of packaging jnr-enxio as a Java library for Debian and noticed that ./src/main/java/jnr/enxio/channels/PollSelectionKey.java still carries an explicit LGPL 3 license header.  Before we upload the package to the archive, I thought it was worth checking whether this file is (still) LGPL 3, or if perhaps it is Apache 2.0 like the other files and was just missed during an update.

Thank you,
tony

**Comment by headius** [comment]
It should be Apache 2.0, and I'll get that fixed.

**Comment by headius** [comment]
Fixed in 07e4ad5f42bb4ff354480785f0a14e7f5bb9d17e.

**Comment by tmancill** [comment]
Thank you!
